[package]
name = "jskeu"
version = "0.1.0"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]
edition = "2018"



[dependencies]
framebuffer = "0.3"
#nix = "0.22"
evdev = "0.11"



[build-dependencies]
cc = "1.0"


