
# *.zcc and *.zar are "zig cc" and "zig ar" wrapper scripts
# which make cross-compilation trivial by leveraging
# the zig & llvm community.
# They live in tool_shims/

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu.zcc"
ar = "x86_64-unknown-linux-gnu.zar"


[target.x86_64-pc-windows-gnu]
linker = "x86_64-pc-windows-gnu.zcc"
ar = "x86_64-pc-windows-gnu.zar"


[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin.zcc"
ar = "x86_64-apple-darwin.zar"


[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin.zcc"
ar = "aarch64-apple-darwin.zar"


